
title: Dung Q.Le
subtitle: Philosophy of Nursing
email: lqdung3@gmail.com
description: "Cảm ơn bạn đã đến với trang của tôi. Đây là nơi chia sẻ mọi điều trong cuộc sống."
github_username: lqdungdt
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Asia/Ho_Chi_Minh

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Lê Quốc Dũng, PhD"
  avatar : "/assets/images/avatar.jpg"
  bio    : "Chia sẻ mọi điều trong cuộc sống."
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://lqdungdt.github.io/lqdung1/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/lqdungdt/"


footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      show_date: true
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/


